name: Update Scholar Stats
on:
  schedule:
    - cron: "0 12 * * *"  # 每天UTC时间12点运行

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Python Script
      run: |
        python scripts/scholar.py
        git config user.name "GitHub Actions"
        git commit -am "Update scholar stats"
        git push